import { PracticeQuestion } from "@/types";

export const readingQuestions: PracticeQuestion[] = [
  {
    id: "r-tfng-001",
    skill: "reading",
    questionType: "true_false_not_given",
    difficulty: 2,
    title: "Urban trees and temperature",
    passage: "Researchers comparing several city districts found that streets with mature tree cover were cooler during afternoon heat than nearby streets with little shade. The effect was most noticeable on clear summer days. The study did not examine whether residents in greener districts used less air conditioning.",
    instruction: "Choose TRUE, FALSE or NOT GIVEN.",
    prompt: "The study proved that people living near mature trees used less air conditioning.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correctAnswer: "NOT GIVEN",
    explanation: {
      testedSkill: "Distinguishing missing information from contradiction.",
      evidence: "The passage says the study did not examine residents' air-conditioning use.",
      whyCorrect: "Because energy use was not investigated, the statement cannot be confirmed or contradicted from the text.",
      trap: "The cooler-street finding makes reduced air-conditioning use sound logical, but IELTS Reading requires textual evidence rather than a reasonable assumption.",
      nextTime: "When a statement adds a new consequence, ask whether the passage actually measures or states that consequence.",
    },
    errorCategory: "not_given_confusion",
  },
  {
    id: "r-tfng-002",
    skill: "reading",
    questionType: "true_false_not_given",
    difficulty: 2,
    title: "Urban trees and temperature",
    passage: "Researchers comparing several city districts found that streets with mature tree cover were cooler during afternoon heat than nearby streets with little shade. The effect was most noticeable on clear summer days. The study did not examine whether residents in greener districts used less air conditioning.",
    instruction: "Choose TRUE, FALSE or NOT GIVEN.",
    prompt: "The cooling effect of mature trees was strongest on clear summer days.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correctAnswer: "TRUE",
    explanation: {
      testedSkill: "Matching a statement to directly stated evidence.",
      evidence: "The passage says the effect was 'most noticeable on clear summer days'.",
      whyCorrect: "Most noticeable is a direct paraphrase of strongest in this context.",
      trap: "The wording changes from 'most noticeable' to 'strongest', so searching only for identical words may cause hesitation.",
      nextTime: "Match meaning, not exact vocabulary. IELTS often paraphrases the evidence.",
    },
    errorCategory: "paraphrase_failure",
  },
  {
    id: "r-mcq-001",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: 3,
    title: "Learning through retrieval",
    passage: "In one classroom experiment, students read the same scientific text. One group reread the material several times, while another closed the text and tried to recall its main ideas before checking what they had missed. Both groups spent approximately the same amount of time studying. A week later, the recall group remembered more of the material, although many students had initially believed rereading would be more effective.",
    instruction: "Choose the best answer.",
    prompt: "What was surprising about the experiment?",
    options: [
      "The recall group studied for much longer.",
      "Students expected rereading to work better than it did.",
      "The scientific text was too difficult for both groups.",
      "The rereading group remembered almost nothing.",
    ],
    correctAnswer: "Students expected rereading to work better than it did.",
    explanation: {
      testedSkill: "Identifying the author's contrast and main point.",
      evidence: "The passage contrasts better later performance from recall with students' initial belief that rereading would be more effective.",
      whyCorrect: "The surprise is the mismatch between expectation and measured performance.",
      trap: "Options about study time and extreme failure sound plausible but are contradicted or unsupported.",
      nextTime: "For multiple choice, compare every option against the passage and eliminate claims that exaggerate or reverse the evidence.",
    },
    errorCategory: "strategy_error",
  },
  {
    id: "r-sentence-001",
    skill: "reading",
    questionType: "sentence_completion",
    difficulty: 3,
    title: "Learning through retrieval",
    passage: "In one classroom experiment, students read the same scientific text. One group reread the material several times, while another closed the text and tried to recall its main ideas before checking what they had missed. Both groups spent approximately the same amount of time studying. A week later, the recall group remembered more of the material, although many students had initially believed rereading would be more effective.",
    instruction: "Complete the sentence with ONE WORD from the passage.",
    prompt: "Before checking the text again, the second group tried to ______ its main ideas.",
    correctAnswer: "recall",
    explanation: {
      testedSkill: "Locating a precise word that fits both meaning and grammar.",
      evidence: "The passage says the group 'tried to recall its main ideas'.",
      whyCorrect: "Recall is copied exactly from the passage and fits grammatically after 'tried to'.",
      trap: "A synonym such as 'remember' has the right meaning but violates the instruction to use a word from the passage.",
      nextTime: "Check both the word limit and whether the task requires words taken directly from the passage.",
    },
    errorCategory: "word_limit",
  },
  {
    id: "r-ynng-001",
    skill: "reading",
    questionType: "yes_no_not_given",
    difficulty: 3,
    title: "Remote work and creativity",
    passage: "Some managers argue that spontaneous office conversations are essential for creativity. However, several design teams in the survey reported that remote work improved the quality of individual preparation before group meetings. The authors conclude that neither location automatically produces better ideas; the way teams structure collaboration appears to matter more.",
    instruction: "Choose YES, NO or NOT GIVEN according to the writer's view.",
    prompt: "The authors believe office-based teams are inherently more creative than remote teams.",
    options: ["YES", "NO", "NOT GIVEN"],
    correctAnswer: "NO",
    explanation: {
      testedSkill: "Recognising the writer's position.",
      evidence: "The authors state that neither location automatically produces better ideas.",
      whyCorrect: "That conclusion directly rejects the claim that office-based teams are inherently more creative.",
      trap: "The first sentence reports what some managers argue, but it is not the authors' conclusion.",
      nextTime: "In YES/NO/NOT GIVEN, distinguish another person's opinion from the writer's own position.",
    },
    errorCategory: "misread_question",
  },
  {
    id: "r-mcq-002",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: 4,
    title: "Remote work and creativity",
    passage: "Some managers argue that spontaneous office conversations are essential for creativity. However, several design teams in the survey reported that remote work improved the quality of individual preparation before group meetings. The authors conclude that neither location automatically produces better ideas; the way teams structure collaboration appears to matter more.",
    instruction: "Choose the best answer.",
    prompt: "What do the authors identify as the more important factor?",
    options: [
      "How frequently managers visit the office",
      "How teams organise collaboration",
      "How long employees work alone",
      "How creative the industry is",
    ],
    correctAnswer: "How teams organise collaboration",
    explanation: {
      testedSkill: "Locating a paraphrased conclusion.",
      evidence: "The final sentence says 'the way teams structure collaboration appears to matter more'.",
      whyCorrect: "Organise collaboration paraphrases structure collaboration.",
      trap: "The passage mentions individual preparation, but it does not say time spent alone is the decisive factor.",
      nextTime: "When a question asks for the author's conclusion, give extra weight to explicit concluding language.",
    },
    errorCategory: "paraphrase_failure",
  },
  {
    id: "r-tfng-003",
    skill: "reading",
    questionType: "true_false_not_given",
    difficulty: 4,
    title: "Restoring wetlands",
    passage: "A coastal restoration programme replaced sections of concrete flood barrier with regenerated salt marsh. Engineers observed that the marsh reduced wave energy before storms reached the remaining sea wall. Maintenance costs for the wall fell over the next five years, but the project team cautioned that the approach would not be suitable for every coastline.",
    instruction: "Choose TRUE, FALSE or NOT GIVEN.",
    prompt: "The restoration team recommended replacing all concrete sea walls with salt marsh.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correctAnswer: "FALSE",
    explanation: {
      testedSkill: "Recognising contradiction through qualification.",
      evidence: "The team cautioned that the approach would not be suitable for every coastline.",
      whyCorrect: "A recommendation to replace all sea walls directly conflicts with the stated limitation.",
      trap: "The passage is positive about the trial, which can tempt you to generalise beyond what the authors claim.",
      nextTime: "Watch absolute words such as 'all', 'always' and 'every'; compare them with qualifications in the text.",
    },
    errorCategory: "inference",
  },
  {
    id: "r-sentence-002",
    skill: "reading",
    questionType: "sentence_completion",
    difficulty: 4,
    title: "Restoring wetlands",
    passage: "A coastal restoration programme replaced sections of concrete flood barrier with regenerated salt marsh. Engineers observed that the marsh reduced wave energy before storms reached the remaining sea wall. Maintenance costs for the wall fell over the next five years, but the project team cautioned that the approach would not be suitable for every coastline.",
    instruction: "Complete the sentence with ONE WORD from the passage.",
    prompt: "The regenerated marsh reduced ______ energy before storms reached the sea wall.",
    correctAnswer: "wave",
    explanation: {
      testedSkill: "Locating a precise word that completes a paraphrased sentence.",
      evidence: "The passage states that the marsh 'reduced wave energy'.",
      whyCorrect: "Wave is taken directly from the passage and completes the noun phrase correctly.",
      trap: "The question changes the surrounding sentence, so you still need to locate the exact relationship in the passage.",
      nextTime: "For completion tasks, confirm both meaning and grammar, then check that your word is actually present in the passage.",
    },
    errorCategory: "strategy_error",
  },
];

export const listeningQuestions: PracticeQuestion[] = [
  {
    id: "l-human-orinoco-001",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 2,
    title: "Human listening · descriptive nonfiction",
    audioSource: {
      id: "lv-orinoco-body-painting",
      url: "https://archive.org/download/coffeebreak003_1001_librivox/coffeebreak003_bodypaintingorinoco_humboldt_mfs_64kb.mp3",
      reader: "Mark F. Smith",
      sourceTitle: "Body Painting of the Orinoco Indians",
      sourcePage: "https://librivox.org/coffee-break-collection-003-nature/",
      duration: "10:54",
      provider: "LibriVox",
      licenseNote: "LibriVox human recording. LibriVox states its recordings are public domain in the USA; audio is streamed from the Internet Archive.",
    },
    instruction: "Listen to the recording and choose the best answer.",
    prompt: "What is the central subject of the recording?",
    options: [
      "The use of pigments and body decoration among peoples of the Orinoco region",
      "The construction of European settlements along the Orinoco",
      "Methods of commercial fishing on the Orinoco",
      "The development of modern river transport",
    ],
    correctAnswer: "The use of pigments and body decoration among peoples of the Orinoco region",
    explanation: {
      testedSkill: "Identifying the main subject of a long spoken passage.",
      evidence: "The recording is an account focused on body painting and pigments among Indigenous communities of the Orinoco region.",
      whyCorrect: "The first option captures the sustained topic of the recording rather than a minor geographic detail.",
      trap: "Long recordings contain many place names and side details; choosing one of them as the main topic is a common listening trap.",
      nextTime: "For main-topic questions, track what the speaker repeatedly returns to instead of selecting the first specific detail you recognise.",
    },
    errorCategory: "strategy_error",
  },
  {
    id: "l-human-emu-001",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 3,
    title: "Human listening · academic history",
    audioSource: {
      id: "lv-etymology-emu",
      url: "https://archive.org/download/coffeebreak003_1001_librivox/coffeebreak003_etymologyemu_mcclymont_cmc_64kb.mp3",
      reader: "Chris Caron",
      sourceTitle: "The Etymology of the Name Emu",
      sourcePage: "https://librivox.org/coffee-break-collection-003-nature/",
      duration: "04:46",
      provider: "LibriVox",
      licenseNote: "LibriVox human recording. LibriVox states its recordings are public domain in the USA; audio is streamed from the Internet Archive.",
    },
    instruction: "Listen to the recording and choose the best answer.",
    prompt: "According to the speaker, the early forms “eme” and “emia” most likely referred to which bird?",
    options: ["A cassowary", "A crane", "An ostrich", "A modern Australian emu"],
    correctAnswer: "A cassowary",
    explanation: {
      testedSkill: "Listening for a historically qualified definition.",
      evidence: "The speaker explains that the early 'eme' or 'emia' was probably a cassowary, likely from Ceram.",
      whyCorrect: "The passage distinguishes the earlier name from the modern Australian emu.",
      trap: "The familiar modern meaning of 'emu' can override what the historical passage actually says.",
      nextTime: "When a speaker discusses word origins, separate the modern meaning from the earlier referent.",
    },
    errorCategory: "attention_loss",
  },
  {
    id: "l-human-weather-001",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 3,
    title: "Human listening · practical lecture",
    audioSource: {
      id: "lv-forecasting-weather",
      url: "https://archive.org/download/coffeebreak003_1001_librivox/coffeebreak003_forecastingweather_gibson_tg_64kb.mp3",
      reader: "TriciaG",
      sourceTitle: "Forecasting the Weather",
      sourcePage: "https://librivox.org/coffee-break-collection-003-nature/",
      duration: "09:54",
      provider: "LibriVox",
      licenseNote: "LibriVox human recording. LibriVox states its recordings are public domain in the USA; audio is streamed from the Internet Archive.",
    },
    instruction: "Listen to the recording and choose the best answer.",
    prompt: "What do low clouds moving swiftly indicate in the recording?",
    options: [
      "Coolness and rain",
      "Dry weather for twelve hours",
      "A warm south wind",
      "Clear weather with falling temperatures",
    ],
    correctAnswer: "Coolness and rain",
    explanation: {
      testedSkill: "Listening for a specific detail inside a longer instructional passage.",
      evidence: "In the section on clouds, the speaker states that low clouds moving swiftly indicate coolness and rain.",
      whyCorrect: "This option reproduces the meaning of the stated weather sign.",
      trap: "The recording lists many weather signs in quick succession, so nearby rules can easily be confused.",
      nextTime: "Before listening, identify the exact noun phrase in the question—here 'low clouds moving swiftly'—and wait for its matching rule.",
    },
    errorCategory: "attention_loss",
  },
  {
    id: "l-human-julygrass-001",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 3,
    title: "Human listening · descriptive prose",
    audioSource: {
      id: "lv-july-grass",
      url: "https://archive.org/download/coffeebreak003_1001_librivox/coffeebreak003_julygrass_jefferies_rg_64kb.mp3",
      reader: "Ruth Golding",
      sourceTitle: "The July Grass",
      sourcePage: "https://librivox.org/coffee-break-collection-003-nature/",
      duration: "10:22",
      provider: "LibriVox",
      licenseNote: "LibriVox human recording. LibriVox states its recordings are public domain in the USA; audio is streamed from the Internet Archive.",
    },
    instruction: "Listen to the recording and choose the best answer.",
    prompt: "What does the narrator say the scarlet-spotted fly does not care about?",
    options: [
      "The names of the different grasses",
      "The strength of the wind",
      "The colour of its own wings",
      "The presence of children nearby",
    ],
    correctAnswer: "The names of the different grasses",
    explanation: {
      testedSkill: "Recognising a contrast between description and the narrator's point.",
      evidence: "The narrator lists several botanical names and says that names mean nothing to the fly.",
      whyCorrect: "The fly simply moves through the grass without concern for human classification.",
      trap: "The passage also mentions wind, colour and children, but those details serve the description rather than the specific contrast asked about.",
      nextTime: "When several concrete details appear close together, listen for the speaker's explicit contrast or judgement.",
    },
    errorCategory: "distractor",
  },
  {
    id: "l-human-magnetism-001",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 4,
    title: "Human listening · science",
    audioSource: {
      id: "lv-curious-magnetism",
      url: "https://archive.org/download/coffeebreak003_1001_librivox/coffeebreak003_magnetism_scientameric_trv_64kb.mp3",
      reader: "trviscelli",
      sourceTitle: "Curious Facts in Magnetism",
      sourcePage: "https://librivox.org/coffee-break-collection-003-nature/",
      duration: "04:57",
      provider: "LibriVox",
      licenseNote: "LibriVox human recording. LibriVox states its recordings are public domain in the USA; audio is streamed from the Internet Archive.",
    },
    instruction: "Listen to the recording and choose the best answer.",
    prompt: "What happens when a bar of iron is brought end-on near a magnetic pole?",
    options: [
      "It becomes an induced magnet",
      "It permanently loses all magnetic properties",
      "It immediately develops two equal neutral points",
      "It is repelled regardless of orientation",
    ],
    correctAnswer: "It becomes an induced magnet",
    explanation: {
      testedSkill: "Following a scientific cause-and-effect explanation.",
      evidence: "The speaker explains that a bar of iron placed near a magnetic pole becomes an induced magnet.",
      whyCorrect: "That is the direct physical effect described before the speaker discusses how its magnetism is distributed.",
      trap: "The passage discusses a claimed neutral line, which can make 'neutral point' sound like the expected answer.",
      nextTime: "Separate the initial observed effect from later discussion about how the effect behaves.",
    },
    errorCategory: "inference",
  },
  {
    id: "l-human-climate-001",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 4,
    title: "Human listening · scientific argument",
    audioSource: {
      id: "lv-modification-climate",
      url: "https://archive.org/download/coffeebreak003_1001_librivox/coffeebreak003_modificationclimate_wallace_mw_64kb.mp3",
      reader: "Michael Wolf",
      sourceTitle: "Modification of Our Climate",
      sourcePage: "https://librivox.org/coffee-break-collection-003-nature/",
      duration: "10:55",
      provider: "LibriVox",
      licenseNote: "LibriVox human recording. LibriVox states its recordings are public domain in the USA; audio is streamed from the Internet Archive.",
    },
    instruction: "Listen to the recording and choose the best answer.",
    prompt: "What does the speaker say is certain about climate during the past two or three thousand years?",
    options: [
      "It has been significantly modified",
      "It has remained almost unchanged",
      "It has become continuously colder",
      "It has followed an exactly predictable cycle",
    ],
    correctAnswer: "It has been significantly modified",
    explanation: {
      testedSkill: "Distinguishing a speaker's firm claim from hypotheses discussed around it.",
      evidence: "The speaker contrasts predictions and theories with the statement that one thing is quite certain: climate has been much modified within the past two or three thousand years.",
      whyCorrect: "The wording marks this as the speaker's confident conclusion rather than a speculative theory.",
      trap: "The passage mentions predictions about extreme cold and long climate cycles, but those are introduced as views rather than the central certainty.",
      nextTime: "Listen for stance markers such as 'it is certain', 'we know', 'it is possible' and 'some argue'.",
    },
    errorCategory: "strategy_error",
  },
  {
    id: "l-human-pigeon-001",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 4,
    title: "Human listening · conservation",
    audioSource: {
      id: "lv-passenger-pigeon",
      url: "https://archive.org/download/coffeebreak003_1001_librivox/coffeebreak003_passengerpigeon_hornaday_bt_64kb.mp3",
      reader: "Bellona Times",
      sourceTitle: "The Passenger Pigeon — from Our Vanishing Wild Life",
      sourcePage: "https://librivox.org/coffee-break-collection-003-nature/",
      duration: "10:53",
      provider: "LibriVox",
      licenseNote: "LibriVox human recording. LibriVox states its recordings are public domain in the USA; audio is streamed from the Internet Archive.",
    },
    instruction: "Listen to the recording and choose the best answer.",
    prompt: "What cause does the speaker emphasise for the disappearance of enormous passenger-pigeon populations?",
    options: [
      "Systematic large-scale slaughter by people",
      "A sudden infectious disease",
      "Competition from imported bird species",
      "A single period of unusually severe winter weather",
    ],
    correctAnswer: "Systematic large-scale slaughter by people",
    explanation: {
      testedSkill: "Identifying the principal cause in an argumentative historical passage.",
      evidence: "The passage says the millions of birds disappeared through systematic, wholesale slaughter for market and food.",
      whyCorrect: "Human killing is presented as the direct explanation for the collapse.",
      trap: "Long historical passages can mention habitat, geography and weather, but the speaker's causal emphasis matters more than background detail.",
      nextTime: "When asked for cause, listen for strong causal language rather than collecting every problem mentioned.",
    },
    errorCategory: "inference",
  },
  {
    id: "l-human-winter-001",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 4,
    title: "Human listening · reflective monologue",
    audioSource: {
      id: "lv-thoreau-winter",
      url: "https://archive.org/download/coffeebreak003_1001_librivox/coffeebreak003_winterjournal_thoreau_sa_64kb.mp3",
      reader: "Sue Anderson",
      sourceTitle: "Winter Journal, Entry February 13, 1859",
      sourcePage: "https://librivox.org/coffee-break-collection-003-nature/",
      duration: "05:39",
      provider: "LibriVox",
      licenseNote: "LibriVox human recording. LibriVox states its recordings are public domain in the USA; audio is streamed from the Internet Archive.",
    },
    instruction: "Listen to the recording and choose the best answer.",
    prompt: "What practical advantage of winter does the speaker describe?",
    options: [
      "Frozen waterways become new walking routes",
      "Snow makes the countryside easier to farm",
      "Cold weather increases the number of travellers",
      "Winter reduces the distance between towns",
    ],
    correctAnswer: "Frozen waterways become new walking routes",
    explanation: {
      testedSkill: "Extracting a practical point from descriptive language.",
      evidence: "The speaker says winter makes walking possible where it was not possible in summer and describes the frozen river and its branches as highways.",
      whyCorrect: "Ice opens routes across territory that could not be walked in the same way during summer.",
      trap: "The recording contains vivid descriptions of snow, light and stillness that can distract from the practical point in the question.",
      nextTime: "When the question asks for an advantage, listen for concrete changes in what the speaker can do.",
    },
    errorCategory: "paraphrase_failure",
  },
];

export const practiceQuestions = [...readingQuestions, ...listeningQuestions];

export function getQuestionsForSkill(skill: "reading" | "listening") {
  return skill === "reading" ? readingQuestions : listeningQuestions;
}

export function getQuestionById(id: string) {
  return practiceQuestions.find((question) => question.id === id);
}
