import { PracticeQuestion } from "@/types";

export const readingQuestions: PracticeQuestion[] = [
  {
    id: "r-tfng-001",
    skill: "reading",
    questionType: "true_false_not_given",
    difficulty: 2,
    title: "Urban trees and temperature",
    passage: "Researchers comparing several city districts found that streets with mature tree cover were cooler during afternoon heat than nearby streets with little shade. The effect was most noticeable on clear summer days. The study did not examine whether residents in greener districts used less air conditioning.",
    instruction: "Choose TRUE, FALSE or NOT GIVEN.",
    prompt: "The study proved that people living near mature trees used less air conditioning.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correctAnswer: "NOT GIVEN",
    explanation: {
      testedSkill: "Distinguishing missing information from contradiction.",
      evidence: "The passage says the study did not examine residents' air-conditioning use.",
      whyCorrect: "Because energy use was not investigated, the statement cannot be confirmed or contradicted from the text.",
      trap: "The cooler-street finding makes reduced air-conditioning use sound logical, but IELTS Reading requires textual evidence rather than a reasonable assumption.",
      nextTime: "When a statement adds a new consequence, ask whether the passage actually measures or states that consequence.",
    },
    errorCategory: "not_given_confusion",
  },
  {
    id: "r-tfng-002",
    skill: "reading",
    questionType: "true_false_not_given",
    difficulty: 2,
    title: "Urban trees and temperature",
    passage: "Researchers comparing several city districts found that streets with mature tree cover were cooler during afternoon heat than nearby streets with little shade. The effect was most noticeable on clear summer days. The study did not examine whether residents in greener districts used less air conditioning.",
    instruction: "Choose TRUE, FALSE or NOT GIVEN.",
    prompt: "The cooling effect of mature trees was strongest on clear summer days.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correctAnswer: "TRUE",
    explanation: {
      testedSkill: "Matching a statement to directly stated evidence.",
      evidence: "The passage says the effect was 'most noticeable on clear summer days'.",
      whyCorrect: "Most noticeable is a direct paraphrase of strongest in this context.",
      trap: "The wording changes from 'most noticeable' to 'strongest', so searching only for identical words may cause hesitation.",
      nextTime: "Match meaning, not exact vocabulary. IELTS often paraphrases the evidence.",
    },
    errorCategory: "paraphrase_failure",
  },
  {
    id: "r-mcq-001",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: 3,
    title: "Learning through retrieval",
    passage: "In one classroom experiment, students read the same scientific text. One group reread the material several times, while another closed the text and tried to recall its main ideas before checking what they had missed. Both groups spent approximately the same amount of time studying. A week later, the recall group remembered more of the material, although many students had initially believed rereading would be more effective.",
    instruction: "Choose the best answer.",
    prompt: "What was surprising about the experiment?",
    options: [
      "The recall group studied for much longer.",
      "Students expected rereading to work better than it did.",
      "The scientific text was too difficult for both groups.",
      "The rereading group remembered almost nothing.",
    ],
    correctAnswer: "Students expected rereading to work better than it did.",
    explanation: {
      testedSkill: "Identifying the author's contrast and main point.",
      evidence: "The passage contrasts better later performance from recall with students' initial belief that rereading would be more effective.",
      whyCorrect: "The surprise is the mismatch between expectation and measured performance.",
      trap: "Options about study time and extreme failure sound plausible but are contradicted or unsupported.",
      nextTime: "For multiple choice, compare every option against the passage and eliminate claims that exaggerate or reverse the evidence.",
    },
    errorCategory: "strategy_error",
  },
  {
    id: "r-sentence-001",
    skill: "reading",
    questionType: "sentence_completion",
    difficulty: 3,
    title: "Learning through retrieval",
    passage: "In one classroom experiment, students read the same scientific text. One group reread the material several times, while another closed the text and tried to recall its main ideas before checking what they had missed. Both groups spent approximately the same amount of time studying. A week later, the recall group remembered more of the material, although many students had initially believed rereading would be more effective.",
    instruction: "Complete the sentence with ONE WORD from the passage.",
    prompt: "Before checking the text again, the second group tried to ______ its main ideas.",
    correctAnswer: "recall",
    explanation: {
      testedSkill: "Locating a precise word that fits both meaning and grammar.",
      evidence: "The passage says the group 'tried to recall its main ideas'.",
      whyCorrect: "Recall is copied exactly from the passage and fits grammatically after 'tried to'.",
      trap: "A synonym such as 'remember' has the right meaning but violates the instruction to use a word from the passage.",
      nextTime: "Check both the word limit and whether the task requires words taken directly from the passage.",
    },
    errorCategory: "word_limit",
  },
  {
    id: "r-ynng-001",
    skill: "reading",
    questionType: "yes_no_not_given",
    difficulty: 3,
    title: "Remote work and creativity",
    passage: "Some managers argue that spontaneous office conversations are essential for creativity. However, several design teams in the survey reported that remote work improved the quality of individual preparation before group meetings. The authors conclude that neither location automatically produces better ideas; the way teams structure collaboration appears to matter more.",
    instruction: "Choose YES, NO or NOT GIVEN according to the writer's view.",
    prompt: "The authors believe office-based teams are inherently more creative than remote teams.",
    options: ["YES", "NO", "NOT GIVEN"],
    correctAnswer: "NO",
    explanation: {
      testedSkill: "Recognising the writer's position.",
      evidence: "The authors state that neither location automatically produces better ideas.",
      whyCorrect: "That conclusion directly rejects the claim that office-based teams are inherently more creative.",
      trap: "The first sentence reports what some managers argue, but it is not the authors' conclusion.",
      nextTime: "In YES/NO/NOT GIVEN, distinguish another person's opinion from the writer's own position.",
    },
    errorCategory: "misread_question",
  },
  {
    id: "r-mcq-002",
    skill: "reading",
    questionType: "multiple_choice",
    difficulty: 4,
    title: "Remote work and creativity",
    passage: "Some managers argue that spontaneous office conversations are essential for creativity. However, several design teams in the survey reported that remote work improved the quality of individual preparation before group meetings. The authors conclude that neither location automatically produces better ideas; the way teams structure collaboration appears to matter more.",
    instruction: "Choose the best answer.",
    prompt: "What do the authors identify as the more important factor?",
    options: [
      "How frequently managers visit the office",
      "How teams organise collaboration",
      "How long employees work alone",
      "How creative the industry is",
    ],
    correctAnswer: "How teams organise collaboration",
    explanation: {
      testedSkill: "Locating a paraphrased conclusion.",
      evidence: "The final sentence says 'the way teams structure collaboration appears to matter more'.",
      whyCorrect: "Organise collaboration paraphrases structure collaboration.",
      trap: "The passage mentions individual preparation, but it does not say time spent alone is the decisive factor.",
      nextTime: "When a question asks for the author's conclusion, give extra weight to explicit concluding language.",
    },
    errorCategory: "paraphrase_failure",
  },
  {
    id: "r-tfng-003",
    skill: "reading",
    questionType: "true_false_not_given",
    difficulty: 4,
    title: "Restoring wetlands",
    passage: "A coastal restoration programme replaced sections of concrete flood barrier with regenerated salt marsh. Engineers observed that the marsh reduced wave energy before storms reached the remaining sea wall. Maintenance costs for the wall fell over the next five years, but the project team cautioned that the approach would not be suitable for every coastline.",
    instruction: "Choose TRUE, FALSE or NOT GIVEN.",
    prompt: "The restoration team recommended replacing all concrete sea walls with salt marsh.",
    options: ["TRUE", "FALSE", "NOT GIVEN"],
    correctAnswer: "FALSE",
    explanation: {
      testedSkill: "Recognising contradiction through qualification.",
      evidence: "The team cautioned that the approach would not be suitable for every coastline.",
      whyCorrect: "A recommendation to replace all sea walls directly conflicts with the stated limitation.",
      trap: "The passage is positive about the trial, which can tempt you to generalise beyond what the authors claim.",
      nextTime: "Watch absolute words such as 'all', 'always' and 'every'; compare them with qualifications in the text.",
    },
    errorCategory: "inference",
  },
  {
    id: "r-sentence-002",
    skill: "reading",
    questionType: "sentence_completion",
    difficulty: 4,
    title: "Restoring wetlands",
    passage: "A coastal restoration programme replaced sections of concrete flood barrier with regenerated salt marsh. Engineers observed that the marsh reduced wave energy before storms reached the remaining sea wall. Maintenance costs for the wall fell over the next five years, but the project team cautioned that the approach would not be suitable for every coastline.",
    instruction: "Complete the sentence with ONE WORD from the passage.",
    prompt: "The regenerated marsh reduced ______ energy before storms reached the sea wall.",
    correctAnswer: "wave",
    explanation: {
      testedSkill: "Locating a precise word that completes a paraphrased sentence.",
      evidence: "The passage states that the marsh 'reduced wave energy'.",
      whyCorrect: "Wave is taken directly from the passage and completes the noun phrase correctly.",
      trap: "The question changes the surrounding sentence, so you still need to locate the exact relationship in the passage.",
      nextTime: "For completion tasks, confirm both meaning and grammar, then check that your word is actually present in the passage.",
    },
    errorCategory: "strategy_error",
  },
];

export const listeningQuestions: PracticeQuestion[] = [
  {
    id: "l-form-001",
    skill: "listening",
    questionType: "form_completion",
    difficulty: 2,
    title: "Community course registration",
    audioText: "Good morning. I'd like to register for the Saturday photography workshop. My name is Elena Morris. That's Morris, M O R R I S. The class starts at nine thirty, but participants should arrive fifteen minutes early.",
    instruction: "Complete the form with ONE WORD.",
    prompt: "Surname: ______",
    correctAnswer: "Morris",
    explanation: {
      testedSkill: "Listening for a spelled proper name.",
      evidence: "The speaker says 'Morris' and then spells M O R R I S.",
      whyCorrect: "Morris is the surname provided during registration.",
      trap: "Names are easy to miss if you start writing before the speaker confirms the spelling.",
      nextTime: "When a name is spelled, wait for the full sequence and check every letter before moving on.",
    },
    errorCategory: "spelling",
  },
  {
    id: "l-form-002",
    skill: "listening",
    questionType: "form_completion",
    difficulty: 2,
    title: "Community course registration",
    audioText: "Good morning. I'd like to register for the Saturday photography workshop. My name is Elena Morris. That's Morris, M O R R I S. The class starts at nine thirty, but participants should arrive fifteen minutes early.",
    instruction: "Complete the form. Write a time.",
    prompt: "Participants should arrive at: ______",
    correctAnswer: "9:15",
    acceptedAnswers: ["9.15", "nine fifteen", "09:15"],
    explanation: {
      testedSkill: "Processing a time calculation from spoken information.",
      evidence: "The class starts at 9:30 and participants should arrive 15 minutes early.",
      whyCorrect: "Fifteen minutes before 9:30 is 9:15.",
      trap: "9:30 is stated explicitly and is therefore a strong distractor.",
      nextTime: "Listen for modifying phrases such as 'early', 'later', 'changed to' and 'instead'.",
    },
    errorCategory: "distractor",
  },
  {
    id: "l-mcq-001",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 3,
    title: "Library orientation",
    audioText: "The quiet study room used to be beside the main entrance, but it has moved to the second floor next to the history collection. The old room is now used for group discussions, so please don't expect silence there.",
    instruction: "Choose the best answer.",
    prompt: "Where is the quiet study room now?",
    options: [
      "Beside the main entrance",
      "Next to the history collection",
      "Inside the group discussion area",
      "On the ground floor near reception",
    ],
    correctAnswer: "Next to the history collection",
    explanation: {
      testedSkill: "Following a correction from old information to current information.",
      evidence: "The speaker says the room 'used to be' near the entrance but 'has moved' next to the history collection.",
      whyCorrect: "The question asks where it is now, so the updated location is required.",
      trap: "The first location is heard earlier and can be selected if you answer too quickly.",
      nextTime: "Do not lock an answer as soon as you hear a matching phrase; listen for corrections and changes.",
    },
    errorCategory: "distractor",
  },
  {
    id: "l-note-001",
    skill: "listening",
    questionType: "note_completion",
    difficulty: 3,
    title: "Library orientation",
    audioText: "The quiet study room used to be beside the main entrance, but it has moved to the second floor next to the history collection. The old room is now used for group discussions, so please don't expect silence there.",
    instruction: "Complete the note with ONE WORD.",
    prompt: "The former quiet room is now used for group ______.",
    correctAnswer: "discussions",
    acceptedAnswers: ["discussion"],
    explanation: {
      testedSkill: "Listening for a key content word in a changed-use description.",
      evidence: "The speaker says the old room is now used for 'group discussions'.",
      whyCorrect: "Discussions completes both the meaning and the grammar of the note.",
      trap: "The phrase 'quiet study room' remains salient, but the question asks about the room's new purpose.",
      nextTime: "Underline time-change cues such as former, now, previously and currently before listening.",
    },
    errorCategory: "attention_loss",
  },
  {
    id: "l-mcq-002",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 4,
    title: "Student project meeting",
    audioText: "We first thought we'd survey commuters at the railway station because the sample would be large. But after discussing access permission, we decided the university bus terminal would be more practical. We can still compare morning and evening travellers there.",
    instruction: "Choose the best answer.",
    prompt: "Where will the students collect their survey data?",
    options: [
      "At the railway station",
      "At the university bus terminal",
      "On several city buses",
      "Online",
    ],
    correctAnswer: "At the university bus terminal",
    explanation: {
      testedSkill: "Tracking a decision after an initial proposal.",
      evidence: "The students first considered the station but then 'decided the university bus terminal would be more practical'.",
      whyCorrect: "The final decision, not the original idea, answers the question.",
      trap: "IELTS Listening frequently presents an attractive early answer and then changes it.",
      nextTime: "Treat words such as 'but', 'however', 'actually' and 'decided' as signals that the answer may change.",
    },
    errorCategory: "distractor",
  },
  {
    id: "l-note-002",
    skill: "listening",
    questionType: "note_completion",
    difficulty: 4,
    title: "Student project meeting",
    audioText: "We first thought we'd survey commuters at the railway station because the sample would be large. But after discussing access permission, we decided the university bus terminal would be more practical. We can still compare morning and evening travellers there.",
    instruction: "Complete the note with ONE WORD.",
    prompt: "One problem with the railway station was obtaining access ______.",
    correctAnswer: "permission",
    explanation: {
      testedSkill: "Listening for a reason embedded before a final decision.",
      evidence: "The speaker refers to 'discussing access permission' before changing the location.",
      whyCorrect: "Permission is the missing noun and directly names the access issue.",
      trap: "The later phrase 'more practical' may distract from the specific reason requested by the note.",
      nextTime: "Predict the grammatical form before listening; here 'access ___' strongly suggests a noun.",
    },
    errorCategory: "attention_loss",
  },
  {
    id: "l-mcq-003",
    skill: "listening",
    questionType: "multiple_choice",
    difficulty: 4,
    title: "Short academic lecture",
    audioText: "People often assume that adding more lanes permanently solves road congestion. In practice, extra capacity can encourage some travellers to drive at times or on routes they previously avoided. As traffic behaviour changes, part of the initial improvement may disappear.",
    instruction: "Choose the best answer.",
    prompt: "What is the lecturer's main point?",
    options: [
      "New roads always make congestion worse immediately.",
      "Extra road capacity can change travel behaviour.",
      "Drivers usually avoid newly constructed roads.",
      "Congestion is mainly caused by poor road maintenance.",
    ],
    correctAnswer: "Extra road capacity can change travel behaviour.",
    explanation: {
      testedSkill: "Identifying the central idea of a short academic explanation.",
      evidence: "The lecturer explains that added capacity encourages travellers to change when and where they drive.",
      whyCorrect: "This option summarises the mechanism described without exaggeration.",
      trap: "Words like 'always' and 'immediately' make the first option much stronger than the lecture.",
      nextTime: "For main-idea questions, prefer the option that covers the whole explanation without adding absolute claims.",
    },
    errorCategory: "inference",
  },
  {
    id: "l-sentence-001",
    skill: "listening",
    questionType: "sentence_completion",
    difficulty: 4,
    title: "Short academic lecture",
    audioText: "People often assume that adding more lanes permanently solves road congestion. In practice, extra capacity can encourage some travellers to drive at times or on routes they previously avoided. As traffic behaviour changes, part of the initial improvement may disappear.",
    instruction: "Complete the sentence with ONE WORD.",
    prompt: "Some of the initial improvement may disappear as travel ______ changes.",
    correctAnswer: "behaviour",
    acceptedAnswers: ["behavior"],
    explanation: {
      testedSkill: "Listening for an academic collocation.",
      evidence: "The lecturer says 'As traffic behaviour changes'.",
      whyCorrect: "Behaviour is the exact key noun needed to complete the idea.",
      trap: "The audio contains several transport nouns, but only 'behaviour' expresses what changes after capacity is added.",
      nextTime: "Use grammar and collocation prediction before the recording reaches the gap.",
    },
    errorCategory: "vocabulary_gap",
  },
];

export const practiceQuestions = [...readingQuestions, ...listeningQuestions];

export function getQuestionsForSkill(skill: "reading" | "listening") {
  return skill === "reading" ? readingQuestions : listeningQuestions;
}

export function getQuestionById(id: string) {
  return practiceQuestions.find((question) => question.id === id);
}
